# Generated by Django 4.1.2 on 2023-03-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_dept_alter_department_deptid'),
        ('account', '0007_remove_user_branch_remove_user_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
    ]
