# Generated by Django 4.1.2 on 2023-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('branche', models.CharField(max_length=100)),
                ('section', models.IntegerField()),
                ('day', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
