# Generated by Django 4.1.2 on 2023-03-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_lecture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lecture',
        ),
    ]
