# Generated by Django 4.1.2 on 2023-03-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_lecture'),
        ('account', '0012_remove_user_department_remove_user_subject_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.ManyToManyField(null=True, to='department.subject'),
        ),
    ]
