# Generated by Django 4.1.2 on 2023-03-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_lecture'),
        ('account', '0013_alter_profile_department_alter_profile_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.ManyToManyField(to='department.subject'),
        ),
    ]
