# Generated by Django 4.1.2 on 2023-03-04 06:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='branche',
            new_name='branch',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='section',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.subject'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
