# Generated by Django 4.1.2 on 2023-03-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_rename_branche_lecture_branch_alter_lecture_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('brachcode', models.IntegerField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
        migrations.AlterField(
            model_name='lecture',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.branch'),
        ),
    ]
