# Generated by Django 4.1.2 on 2023-03-04 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_remove_profile_subject_branch_alter_lecture_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='brachcode',
            new_name='branchcode',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('class_id', models.CharField(max_length=5)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.branch')),
            ],
        ),
    ]
