# Generated by Django 4.1.2 on 2023-03-04 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_rename_brachcode_branch_branchcode_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='period',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
