# Generated by Django 4.1.2 on 2023-03-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_lecture_period_alter_class_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='cid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='department.class'),
            preserve_default=False,
        ),
    ]
