# Generated by Django 4.1.2 on 2023-03-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_lecture_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.ManyToManyField(to='department.subject'),
        ),
    ]
