# Generated by Django 4.1.2 on 2023-03-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='time',
        ),
    ]
