# Generated by Django 4.1.2 on 2023-03-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0013_remove_lecture_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='type',
            field=models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('LAB', 'LAB'), ('OTHERS', 'OTHERS')], max_length=7, null=True),
        ),
    ]
