# Generated by Django 4.1.2 on 2023-03-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0014_lecture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.period'),
        ),
    ]
