# Generated by Django 4.1.2 on 2023-03-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0015_alter_lecture_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='section',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='year',
        ),
    ]
